# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b0707b5494989810e9e0baa19ade84277d166f542257c3e7f688db2ba5552013244d86d62e4874222fad599d32aaf3d826719ab747d705e0d267dc05d43ce892

test:
  secret_key_base: e569f4628f4e55a81005c4b14f8bd16a129fe5accdd619dbe0a3374c32d3de756ade7ffb5366f11ae70ee96d1aaa545b360816dd26447c6474114a2e0b47bffa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
